# Generated by Django 4.2.4 on 2023-08-23 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheeseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Placed", "Placed"),
                            ("Accepted", "Accepted"),
                            ("Preparing", "Preparing"),
                            ("Dispatched", "Dispatched"),
                            ("Delivered", "Delivered"),
                        ],
                        default="Placed",
                        max_length=20,
                    ),
                ),
                ("order_time", models.DateTimeField(auto_now_add=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("price", models.FloatField(default=0.0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PizzaBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=180)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Toppings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderPizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cheese_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of Cheese eg: mozzarella, cheddar, parmesan",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.cheesetype",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pizzas",
                        to="orders.order",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.pizza"
                    ),
                ),
                (
                    "pizza_base",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of pizza base eg: thin crust, cheese-burst etc",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.pizzabase",
                    ),
                ),
                (
                    "toppings",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Select up to 5 toppings",
                        related_name="pizzas",
                        to="orders.toppings",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
